/*

01-CreateDB_XXX.sql
6/20/2016 - S.Werner

Creates an empty database for isotropic turbulence data.
This file only creates the PRIMARY filegroup and log file.

Assumes DSP node or similar storage setup with 12-way mirrors.

CTRL-F and replace XXX with slice number of the turbDB you wish to create,
e.g. 201, 202, etc.

*/




USE [master]
GO

/****** Object:  Database [turbdbXXX]    Script Date: 5/11/XXX6 6:05:04 PM ******/
CREATE DATABASE [turbdbXXX]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'turbdbXXX', FILENAME = N'C:\data\data1\sql_db\turbdbXXX.mdf' , SIZE = 102400KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'turbdbXXX_log', FILENAME = N'C:\data\data1\sql_db\turbdbXXX_log.ldf' , SIZE = 2048000KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [turbdbXXX] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [turbdbXXX].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [turbdbXXX] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [turbdbXXX] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [turbdbXXX] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [turbdbXXX] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [turbdbXXX] SET ARITHABORT OFF 
GO

ALTER DATABASE [turbdbXXX] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [turbdbXXX] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [turbdbXXX] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [turbdbXXX] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [turbdbXXX] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [turbdbXXX] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [turbdbXXX] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [turbdbXXX] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [turbdbXXX] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [turbdbXXX] SET  DISABLE_BROKER 
GO

ALTER DATABASE [turbdbXXX] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [turbdbXXX] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [turbdbXXX] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [turbdbXXX] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [turbdbXXX] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [turbdbXXX] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [turbdbXXX] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [turbdbXXX] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [turbdbXXX] SET  MULTI_USER 
GO

ALTER DATABASE [turbdbXXX] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [turbdbXXX] SET DB_CHAINING OFF 
GO

ALTER DATABASE [turbdbXXX] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [turbdbXXX] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [turbdbXXX] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [turbdbXXX] SET  READ_WRITE 
GO

