USE [master]
GO

/****** Object:  Database [test203]    Script Date: 12/16/2015 3:18:41 PM ******/
CREATE DATABASE [test203] ON  PRIMARY 
( NAME = N'PRIMARY1', FILENAME = N'C:\data\data1\sql_db\test203_PRIMARY1.mdf' , SIZE = 10MB , MAXSIZE = UNLIMITED, FILEGROWTH = 10MB ),
FILEGROUP [DATA] 
( NAME = N'DATA1', FILENAME = N'C:\data\data1\sql_db\test203_DATA1.ndf' , SIZE = 25 GB , MAXSIZE = UNLIMITED, FILEGROWTH = 50MB ), 
( NAME = N'DATA2', FILENAME = N'C:\data\data2\sql_db\test203_DATA2.ndf' , SIZE = 25 GB , MAXSIZE = UNLIMITED, FILEGROWTH = 50MB )


 LOG ON 
( NAME = N'test203_log', FILENAME = N'C:\data\data2\sql_db\test203_log.ldf' , SIZE = 500MB , MAXSIZE = 2048GB , FILEGROWTH = 100MB)
GO

--ALTER DATABASE [test203] SET COMPATIBILITY_LEVEL = 100
--GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [test203].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [test203] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [test203] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [test203] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [test203] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [test203] SET ARITHABORT OFF 
GO

ALTER DATABASE [test203] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [test203] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [test203] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [test203] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [test203] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [test203] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [test203] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [test203] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [test203] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [test203] SET  DISABLE_BROKER 
GO

ALTER DATABASE [test203] SET AUTO_UPDATE_STATISTICS_ASYNC ON 
GO

ALTER DATABASE [test203] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [test203] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [test203] SET ALLOW_SNAPSHOT_ISOLATION ON 
GO

ALTER DATABASE [test203] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [test203] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [test203] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [test203] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [test203] SET  MULTI_USER 
GO

ALTER DATABASE [test203] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [test203] SET DB_CHAINING OFF 
GO

ALTER DATABASE [test203] SET  READ_WRITE 
GO



