USE [master]
GO

/****** Object:  Database [TurbScratch]    Script Date: 4/14/2015 12:10:32 PM ******/
CREATE DATABASE [TurbScratch]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'TurbScratch_01', FILENAME = N'C:\data\data1\sql_db\TurbScratch_01.mdf' , SIZE = 102400000KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10%),
( NAME = N'TurbScratch_02', FILENAME = N'C:\data\data2\sql_db\TurbScratch_02.ndf' , SIZE = 102400000KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10%),
( NAME = N'TurbScratch_03', FILENAME = N'C:\data\data3\sql_db\TurbScratch_03.ndf' , SIZE = 102400000KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10%),
( NAME = N'TurbScratch_04', FILENAME = N'C:\data\data4\sql_db\TurbScratch_04.ndf' , SIZE = 102400000KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10%),
( NAME = N'TurbScratch_05', FILENAME = N'C:\data\data5\sql_db\TurbScratch_05.ndf' , SIZE = 102400000KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10%),
( NAME = N'TurbScratch_06', FILENAME = N'C:\data\data6\sql_db\TurbScratch_06.ndf' , SIZE = 102400000KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10%),
( NAME = N'TurbScratch_07', FILENAME = N'C:\data\data7\sql_db\TurbScratch_07.ndf' , SIZE = 102400000KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10%),
( NAME = N'TurbScratch_08', FILENAME = N'C:\data\data8\sql_db\TurbScratch_08.ndf' , SIZE = 102400000KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10%),
( NAME = N'TurbScratch_09', FILENAME = N'C:\data\data9\sql_db\TurbScratch_09.ndf' , SIZE = 102400000KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10%),
( NAME = N'TurbScratch_10', FILENAME = N'C:\data\data10\sql_db\TurbScratch_10.ndf' , SIZE = 102400000KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10%),
( NAME = N'TurbScratch_11', FILENAME = N'C:\data\data11\sql_db\TurbScratch_11.ndf' , SIZE = 102400000KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10%),
( NAME = N'TurbScratch_12', FILENAME = N'C:\data\data12\sql_db\TurbScratch_12.ndf' , SIZE = 102400000KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10%)
 LOG ON 
( NAME = N'TurbScratch_log', FILENAME = N'C:\data\data3\sql_db\TurbScratch_log.ldf' , SIZE = 8192000KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [TurbScratch] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [TurbScratch].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [TurbScratch] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [TurbScratch] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [TurbScratch] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [TurbScratch] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [TurbScratch] SET ARITHABORT OFF 
GO

ALTER DATABASE [TurbScratch] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [TurbScratch] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [TurbScratch] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [TurbScratch] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [TurbScratch] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [TurbScratch] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [TurbScratch] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [TurbScratch] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [TurbScratch] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [TurbScratch] SET  DISABLE_BROKER 
GO

ALTER DATABASE [TurbScratch] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [TurbScratch] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [TurbScratch] SET TRUSTWORTHY ON 
GO

ALTER DATABASE [TurbScratch] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [TurbScratch] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [TurbScratch] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [TurbScratch] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [TurbScratch] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [TurbScratch] SET  MULTI_USER 
GO

ALTER DATABASE [TurbScratch] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [TurbScratch] SET DB_CHAINING OFF 
GO

ALTER DATABASE [TurbScratch] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [TurbScratch] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [TurbScratch] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [TurbScratch] SET  READ_WRITE 
GO


